### ISSUE TITLE
helloworld: remove output file

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-demo-helloworld#14]
When capturing job's `stdout/stderr` support is introduced to REANA, it would be good to simplify the current "hello world" example by not using the output file, but rather printing the greeting on the standard output and capturing that for the end user.  

We could also remove the sleeptime and most of other arguments, so that "hello world" will become as simple as possible. (Perhaps as bare as `$ helloworld.py Joe`.) 

This is because we have other examples that demonstrate these use cases, such as the usage of input/output files in "worldpopulation" example. Or, the progressive printing by tasks can be better addressed by another example, say primer number factorisation or somesuch, that could even use some  parallel techniques to launch calculations in many cluster nodes at once.

The "hello world" example will then remain a very simple introduction to the ecosystem.

**Comment by diegodelemos** [comment]
Depends on https://github.com/reanahub/reana-workflow-engine-yadage/issues/27

**Comment by tiborsimko** [comment]
We decided to keep input and output files, and the stdout/stderr-grabbing work packages are ticketised elsewhere, so we can close this old issue.
