### ISSUE TITLE
docs: add Launch-on-REANA badges

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-demo-helloworld#60]
Add "Launch-on-REANA" badges to the README file.

We have a lot of `reana-*.yaml`, so think about a nice presentation.

We can restrict ourselves to only four badges, cwl/serial/snakemake/yadage.  

We don't have to cover HTCondor or Slurm.

**Comment by tiborsimko** [comment]
Possible badge: "Launch helloworld snakemake on REANA @ CERN" but it could be too wide.

Another option would be to simply write things in text: `Launch helloworld snakemake example: [Launch | REANA]` so that the text is wider and badge nicely shorter.

Anyway, needs some experimenting with Markdown formatting and text placement...

**Comment by VMois** [comment]
> Some ideas if we only keep the badge hosted on [www.reana.io](http://www.reana.io/):

I like the usage of tables and default badges. Especially, the first one - the horizontal table.

**Comment by VMois** [comment]
One thing I am worried about is that we do not have a clear call to action in some demo examples. With 4 badges it might be confusing for a new user to decide what to click on.

Some demo examples have only one workflow type which makes things easier, but, in the case of multiple badges, it would be nice to highlight the default one, for example.

**Comment by tiborsimko** [comment]
You can experiment changing the README and making a PR to see how things will look in the final product.

E.g. if there is only one badge, it can be placed next to "licence: MIT" badge on top, and it can be teh default one, and everything should be rather clear to users. 

However, it may be good to alter the section "Running the example on REANA cloud" occurring down the README file page too, so that people know that they can simply click on a badge as a parallel technique. (See e.g. [CMS open data example](https://github.com/cms-opendata-analyses/DimuonSpectrumNanoAODOutreachAnalysis) that shows badges down in the text.)

This may be especially interesting if we have four badges to display, one for each workflow engine. It may be too much to put them all at the top, since novice users haven't managed to even read what the example is about.  So "Running..." may be a better place; we also have more textual room down there for better presentations and explanations.

(One could combine both techniques: show one simple default badge at the top, and several workflow-specific badges at the bottom in the "Running..." section.)

WRT CWL/Serial/Snakemake/Yadage badges and texts, we should make it rather clear that only one of them is in principle necessary, whatever each user usually uses should catch the eye. Hence I like the proposed text "Launch with Yadage on | REANA@CERN" which seems nicely engaging and which presents the essential of the what is going on in one concise phrase. (Plus it would be clear where things will run, REANA@CERN, for REANA@NYI, REANA@BNL users. Plus it would "pre-warn" non-CERN users that they might not have appropriate rights to run it there.)

If we go this way, then we can generate a set of four badges and host them on `www.reana.io` as well, to avoid depending on external services.  (Via another PR to `www.reana.io`.)

**Comment by VMois** [comment]
Does it makes sense for our self-hosted badge "Launch on REANA" to be changed to "Launch on REANA@CERN"?
